version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
jobs:
  build:
    executor: node
    steps:
      - slack/notify:
          channel: tp-ing-sw
          color: '#42e2f4'
          message: building...
          webhook: xxxxW51M
      - checkout
      - run: npm install
      - run: npm run build
  test:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run test
orbs:
  slack: circleci/slack@3.4.2
