version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - slack/notify:
          channel: C015LT4SQ2D
          color: '#42f44e'
          message: BUILD Finalizada
  test:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - slack/status:
          mentions: 'U0151GNJQ22,U0156TZ3JGM'
orbs:
  slack: circleci/slack@3.4.2
